episode_manager:
  ros__parameters:
    dwell_sec: 5.0  # sec
    goal_source: static
    goal_poses_x: [1.0, 1.0, 0.0, 0.0]
    goal_poses_y: [0.0, 1.0, 1.0, 0.0]
    goal_poses_yaw: [0.0, 90.0, 180.0, 270.0]    
    goals_num: 4
    episodes_num: 1
    action_server: /navigate_to_pose
    episode_pub_topic: /navlearn/episode_event
    fixed_frame: map
    robot_frame: base_link