metrics_compiler:
  ros__parameters:
    csv_path: /home/mihirmk/robot_ws/src/navlearn_benchmarks/benchmark_reports/navlearn_metrics.csv
    json_path: /home/mihirmk/robot_ws/src/navlearn_benchmarks/benchmark_reports/navlearn_run_report.json
    episode_event_topic: /navlearn/episode_event
    control_metric_topic: /navlearn/control_metric
    trajectory_metric_topic: /navlearn/trajectory_metric