name: ROS Humble CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    container: ros:humble-ros-base          # ready-made ROS 2 image
    steps:
      - uses: actions/checkout@v3

      - name: Install colcon & rosdep
        run: |
          apt-get update
          apt-get install -y python3-colcon-common-extensions python3-rosdep git
          rosdep init || true
          rosdep update
          rosdep install --from-paths src --ignore-src -r -y

      - name: Build
        run: colcon build --event-handlers console_cohesion+

      - name: Test
        run: |
          colcon test
          colcon test-result --verbose
