name: ROS Humble CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: ros-tooling/action-ros-ci@v0.4
        with:
          target-ros2-distro: humble
